PAWNS = 'P'
KNIGHTS = 'N'
BISHOPS = 'B'
ROOKS = 'R'
QUEENS = 'Q'
KINGS = 'K'

PIECE_TYPES = (
    PAWNS,
    KNIGHTS,
    BISHOPS,
    ROOKS,
    QUEENS,
    KINGS
)

SHORT_CASTLE = 'O-O'
LONG_CASTLE = 'O-O-O'
ENPASSANT_LEFT = '<-x'
ENPASSANT_RIGHT = 'x->'
PROMOTE_TO_QUEEN = 'promote:' + QUEENS
PROMOTE_TO_ROOK = 'promote:' + ROOKS
PROMOTE_TO_BISHOP = 'promote:' + BISHOPS
PROMOTE_TO_KNIGHT = 'promote:' + KNIGHTS

SPECIAL_MOVES = (
    SHORT_CASTLE,
    LONG_CASTLE,
    ENPASSANT_LEFT,
    ENPASSANT_RIGHT,
    PROMOTE_TO_BISHOP,
    PROMOTE_TO_KNIGHT,
    PROMOTE_TO_ROOK,
    PROMOTE_TO_QUEEN
)
