PAWNS = 'p'
KNIGHTS = 'n'
BISHOPS = 'b'
ROOKS = 'r'
QUEENS = 'q'
KING = 'k'

PIECE_TYPES = (
    PAWNS,
    KNIGHTS,
    BISHOPS,
    ROOKS,
    QUEENS,
)

SHORT_CASTLE = 'O-O'
LONG_CASTLE = 'O-O-O'
ENPASSANT_LEFT = '<-x'
ENPASSANT_RIGHT = 'x->'
PROMOTE_TO_QUEEN = 'promote:' + QUEENS
PROMOTE_TO_ROOK = 'promote:' + ROOKS
PROMOTE_TO_BISHOP = 'promote:' + BISHOPS
PROMOTE_TO_KNIGHT = 'promote:' + KNIGHTS
